# Generated by Django 3.2.7 on 2021-10-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipeingredientimage_extracted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
